#!/bin/sh
target="out/"

fileDir="pages/"
contentDir="content/"
rawDir="raw/"
filesRaw="content/"


#compile
for f in "$fileDir"*; do
	x=$(basename -- "$f")
	echo "$f -> $target$x"
	cat blocks/head.html > "$target$x"
	cat blocks/bg.html   >>"$target$x"
	cat "$f"        >>"$target$x"
	cat blocks/end.html  >>"$target$x"
	if [ -n "$x_targ" ] ;then 
		#rm "$x_targ"
		x_targ=''
	fi
done
cp -r "$contentDir" "$target"
cp -r "$rawDir"* "$target"
#non compiled files
for x in $filesRaw; do
	cp -r "$x" "$target$x"
done

echo "Compilation done"
